universe                = vanilla
executable              = gatherinfo2.sh
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
output                  = out.$(Process)
log                     = log.$(Process)
error                   = err.$(Process)
request_memory          = 128 MB
request_cpus            = 2
request_disk            = 1 * 1024

output       = gpu2.out.$(Process)
log          = gpu2.log.$(Process)
error        = gpu2.err.$(Process)
queue 1

