universe                = vanilla
executable              = gatherinfo.sh
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
output                  = out.$(Process)
log                     = log.$(Process)
error                   = err.$(Process)
request_memory          = 128 MB
request_cpus            = 8
request_disk            = 1 * 1024

output       = testjob.out.$(Process)
log          = testjob.log.$(Process)
error        = testjob.err.$(Process)
queue 5

