universe                = vanilla
executable              = gatherinfo.sh
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
output                  = out.$(Process)
log                     = log.$(Process)
error                   = err.$(Process)
request_memory          = 128 MB
request_cpus            = 8
request_disk            = 1 * 1024

output       = cpu2.out.$(Process)
log          = cpu2.log.$(Process)
error        = cpu2.err.$(Process)
queue 1

