universe                = vanilla
executable              = mpi_run.sh

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files    = mpi1.c

output                  = out.$(Process)
log                     = log.$(Process)
error                   = err.$(Process)

getenv                  = true

machine_count           = 3
request_memory          = 4GB
request_cpus            = 4
request_disk            = 2GB

queue

